apiVersion: apps/v1
kind: Deployment
metadata:
  name: seminaire-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seminaire-service
  template:
    metadata:
      labels:
        app: seminaire-service
    spec:
      containers:
        - name: seminaire-service
          image: salma1819/seminaire_service:v1
          ports:
            - containerPort: 5000
          env:
            - name: RESERVATION_SERVICE_URL
              value: "http://reservation-service:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: seminaire-service
spec:
  selector:
    app: seminaire-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: yousra2302/reservation_service:v1
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  selector:
    app: reservation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: oumkh963/auth_service:v1
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: chaimaeblk2003/notification_service:v1
          ports:
            - containerPort: 8000
          env:
            - name: SEMINAIRE_SERVICE_URL
              value: "http://seminaire-service:5000"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
